export default {
  async fetch(request, env, ctx) {
    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Content-Type": "application/json; charset=utf-8"
    };

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    if (request.method !== "POST") {
      return new Response(JSON.stringify({ error: "Method not allowed. Use POST." }), {
        status: 405,
        headers: corsHeaders
      });
    }

    try {
      const body = await request.json();
      const userPrompt = body.prompt || body.message || "";

      if (!userPrompt) {
        return new Response(JSON.stringify({ error: "Prompt parameter is required." }), {
          status: 400,
          headers: corsHeaders
        });
      }

      const apiKey = env.GEMINI_API_KEY;
      if (!apiKey) {
        return new Response(JSON.stringify({ 
          error: "GEMINI_API_KEY variable is missing in Cloudflare Worker environment settings." 
        }), {
          status: 500,
          headers: corsHeaders
        });
      }

      const geminiEndpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?key=${apiKey}`;

      const systemContext = `You are the SAR AI Mission Copilot for the 'Dancing with SARS' Lunar Control Center (NASA Space Apps Challenge 2026).
Your job is to assist lunar mission planners in evaluating CLPS landing sites at the Lunar South Pole (e.g. Shackleton Crater, Cabeus Crater).
Explain Synthetic Aperture Radar (SAR) concepts like Circular Polarization Ratio (CPR), ice probabilities, permanently shadowed regions (PSRs), and slope hazards in a helpful, concise sci-fi mission tone.
Keep responses short, clear, and focused on space operations.`;

      const geminiPayload = {
        contents: [
          {
            role: "user",
            parts: [
              { text: `${systemContext}\n\nUser Inquiry: ${userPrompt}` }
            ]
          }
        ]
      };

      const response = await fetch(geminiEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(geminiPayload)
      });

      const geminiData = await response.json();

      if (!response.ok) {
        return new Response(JSON.stringify({ 
          error: geminiData.error?.message || "Gemini API gateway returned an error." 
        }), {
          status: response.status,
          headers: corsHeaders
        });
      }

      const replyText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text || "No output generated by Gemini.";

      return new Response(JSON.stringify({ reply: replyText }), {
        status: 200,
        headers: corsHeaders
      });

    } catch (err) {
      return new Response(JSON.stringify({ error: err.message || "Internal Worker Error" }), {
        status: 500,
        headers: corsHeaders
      });
    }
  }
};